services:
  postgres:
    image: postgres
    container_name: hearth-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - hearth-postgres:/var/lib/postgresql/data
    networks:
      - hearth-network

  mongo:
    image: mongo
    container_name: hearth-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - hearth-mongo:/data/db
    networks:
      - hearth-network

  redis:
    image: redis/redis-stack:latest
    container_name: hearth-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - hearth-redis:/data
    networks:
      - hearth-network
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--maxmemory",
        "256mb",
        "--maxmemory-policy",
        "allkeys-lru",
      ]

networks:
  hearth-network:
    driver: bridge

volumes:
  hearth-postgres:
  hearth-mongo:
  hearth-redis:
